
services:

  app:
    build: .
    container_name: fast_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DB_ENGINE}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      DATABASE_POOL_SIZE:
      DB_ENGINE:
      DB_NAME:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      DB_HOST:
      DB_PORT:
      ENVIRONMENT:
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


volumes:
  db-data:
